### ISSUE TITLE
code coverage not counted when using subprocess.Popen()

### ISSUE THREAD

**Issue by cmeeren** [ionelmc/cookiecutter-pylibrary#13] opened 2015-06-04 22:42 UTC
Try as I might (and I've tried a few things for a few hours now), code executed in `subprocess.Popen` calls isn't included in the coverage report. Not on Travis/Coveralls, and not locally. Do you have this problem? Do you have any idea why?
- My repository (see the develop branch): https://github.com/cmeeren/latexdiffcite
- Tests in question: in `tests/test_latexdiffcite.py`, functions `test_run_module` (should test the final line in `__main__.py`) and `test_main` (should test a lot of the otherwise untested stuff in `latexdiffcite.py`).

This may not be due to cookiecutter-pylibrary, but then again it might, and if it boils down to some configuration, then I assume you want to have it working. :)

**Comment by ionelmc** [comment] 2015-06-04 22:52
In that case you need to follow the instructions here: http://nedbatchelder.com/code/coverage/subprocess.html

**Comment by ionelmc** [comment] 2015-06-04 22:55
Also, do you use `pytest` as the test runner?

**Comment by ionelmc** [comment] 2015-06-04 22:58
If you do use `pytest` (and `pytest-cov`) then it should work out of the box - just make sure your `Popen` passes down these env vars: `COV_CORE_SOURCE` and `COV_CORE_CONFIG`.

**Comment by cmeeren** [comment] 2015-06-05 06:46
Thanks. I am passing down all variables, and the two you mention (as well as ``COV_CORE_DATA_FILE`` if that's relevant) are confirmed available to the subprocess (I wrote them to file in the subprocessed script to check).

Still doesn't work, though. I notice in e.g. ``.tox\2.7\Lib\site-packages`` that there is no ``init_cov_core.pth``. Should there be? I tried copying it from my normal Python installation, but still no go. Without it, ``cov_core_init.py`` is not run. With it, ``cov_core_init.py`` is run successfully (I put some ``file.write`` commands there to check), but still the coverage is not changed.

Note that I am trying this with the ``2.7`` environment and run `tox -e 2.7` to test all this.

Do you have any idea what could be wrong?

**Comment by ionelmc** [comment] 2015-06-05 08:09
Hard to say what's going on. If you put the code somewhere I'll take a look.

**Comment by cmeeren** [comment] 2015-06-05 08:14
Code available at https://github.com/cmeeren/latexdiffcite/tree/develop (develop branch)

Thanks!

**Comment by ionelmc** [comment] 2015-06-05 08:18
Is this wrong result?
```
--------------- coverage: platform win32, python 2.7.10-final-0 ---------------
Name                              Stmts   Miss Branch BrMiss     Cover   Missing
--------------------------------------------------------------------------------
src\latexdiffcite\__init__            1      0      0      0   100.00%
src\latexdiffcite\__main__            5      1      2      1    71.43%   12
src\latexdiffcite\latexdiffcite     403     44    119     19    87.93%   139-144, 166-170, 232-235, 239-240, 326-336, 421, 431, 513, 596, 704-706, 807-817, 821
--------------------------------------------------------------------------------
TOTAL                               409     45    121     20    87.74%

========================= 100 passed in 6.47 seconds ==========================
```

**Comment by ionelmc** [comment] 2015-06-05 08:21
I had the `.pth` file in `site-packages`, as expected. Are you using some old virtualenv?

**Comment by cmeeren** [comment] 2015-06-05 08:23
Yes, that's wrong. The function ``test_main`` should ensure a whole lot more coverage in ``src\latexdiffcite\latexdiffcite`` as well as full coverage of ``src\latexdiffcite\__main__``.

I am using ``conda`` to manage my python distributions, and I am launching ``tox -e 2.7`` from an environment with Python 3.4, virtualenv 13.0.1.

**Comment by ionelmc** [comment] 2015-06-05 08:38
Not sure if that `sys.exit()` can be measured - what's missing from `src\latexdiffcite\latexdiffcite` ?

**Comment by cmeeren** [comment] 2015-06-05 08:48
I get the same result if I remove ``sys.exit()``.

``test_main`` launches the module from the command line, just as the user would. This tests more or less everything, whereas in the other tests, I test only parts of the module directly. Most notably, ``main()`` should be run. This also runs ``Files.destroy_tempfiles()`` and ``run_latexdiff()``.

**Comment by cmeeren** [comment] 2015-06-05 11:45
I should mention that I have thought up a way to circumvent this problem (add optional ``args`` argument to the entry point ``main()`` and test ``main()`` directly with the desired arguments, instead of using ``subprocess.Popen``), however that is of course not a general solution to the problem and I would like to get to the bottom of it if possible. :sweat_smile:

**Comment by ionelmc** [comment] 2015-06-05 15:21
I've taken a more in-depth look. It appears you have two separate issues:

* cov-core (pytest-cov's "thing") is sorta broken and doesn't really install the .pth file. I'm considering making my own pytest plugin.
* You cannot get coverage for lines after `if __name__ == "__main__":` by just running the bin (since setuptools' entrypoint is not gonna run that). To trigger those lines you must run something like `Popen([sys.executable, '-m', "packagename", ...])`.

**Comment by cmeeren** [comment] 2015-06-05 16:40
Oh wow, thanks!

1. Is that fixed by simply copying the .pth file manually into the correct tox environments? Could that be automated, for example by including the file in your repo and using some commands in the tox environments to copy it? And is it fundamentally broken in some way, since you're considering making your own instead of just [fixing it](https://github.com/schlamar/pytest-cov)?

2. You are of course entirely right that the entry point does not run the ``if __name__ == "__main__":`` part. But I do have a test (``test_run_module``) that does ``subprocess.Popen(['python', '-m', 'latexdiffcite', '--version'], ...``. The line below ``if __name__ == "__main__":`` still isn't covered. Why is that?

**Comment by ionelmc** [comment] 2015-06-05 16:59
1. Cause I made some PR with some fixes half a year ago to pytest-cov and they still haven't been released. The project is stalled.

2. I've tried locally with something like `subprocess.Popen([sys.executable, '-mfoobar'])` and it work. Maybe there's some issue with pytest-cov. I'm gonna take a look again after I release the fork.

**Comment by cmeeren** [comment] 2015-06-05 17:45
1. They seem to be active on GitHub. You can ask them to transfer the PyPI entry and possibly GitHub repo over to you. Just a tip. :)

**Comment by ionelmc** [comment] 2015-06-05 17:55
Maybe, but I want to get it fixed first, and merge pytest-cov with cov-core - that split is ridiculous :)

**Comment by cmeeren** [comment] 2015-06-05 17:57
Aren't the two the same project now? They live in the same github repo; the [old cov-core repo](https://github.com/schlamar/cov-core) redirects. Forgive me my ignorance.

**Comment by ionelmc** [comment] 2015-06-05 22:57
I've wrote him, lets see what happens. Meanwhile you can take https://github.com/ionelmc/pytest-cover for a spin (use `https://github.com/ionelmc/pytest-cover/archive/master.zip` as the depenendcy).

**Comment by cmeeren** [comment] 2015-06-05 23:10
Where exactly do I put that dependency, and which existing deps do I replace/remove?

**Comment by ionelmc** [comment] 2015-06-05 23:31
Instead of `pytest-cov` use `https://github.com/ionelmc/pytest-cover/archive/master.zip`.

It should be a drop in replacement.

**Comment by cmeeren** [comment] 2015-06-05 23:48
You need to make it dependent on ``coverage``, I got ``ImportError: No module named coverage``.

After adding ``coverage`` to the dependencies, I see that ``pytest-cover.pth`` is installed into the environment. However, I still have the line below ``if __name__ == '__main__':`` in ``__main__.py`` missing from the coverage (the line should be run in ``test_run_module()`` where I call ``subprocess.Popen(['python', '-m', 'latexdiffcite', '--version']``).

**Comment by ionelmc** [comment] 2015-06-06 00:03
Could it be a bug in coverage? What if you add some bogus code in there?

**Comment by cmeeren** [comment] 2015-06-06 14:37
If I add some bogus code below ``if __name__ == '__main__':`` in ``__main__.py``, then the code is executed during ``test_run_module()`` and the line shows up as not covered.

**Comment by ionelmc** [comment] 2015-06-06 15:08
This https://github.com/ionelmc/python-nameless/commit/6faae8f289be49f6b5a595165e17e9f9a5134131 gets me full coverage: https://travis-ci.org/ionelmc/python-nameless/jobs/65685186#L161

What are you doing differently?

**Comment by cmeeren** [comment] 2015-06-06 15:25
Interesting. When I test that commit using ``tox -e 2.7 -r``, the lines inside ``main()`` and ``if __name__ == "__main__"`` are not covered:

```
$ tox -e 2.7 -r
2.7 recreate: C:\Users\Christer\code\python\python-nameless\.tox\2.7
2.7 installdeps: pytest, pytest-capturelog, click, https://github.com/ionelmc/pytest-cover/archive/master.zip
2.7 develop-inst: C:\Users\Christer\code\python\python-nameless
2.7 installed: click==4.0,colorama==0.3.3,coverage==3.7.1,nameless==0.1.0,py==1.4.28,pytest==2.7.1,pytest-capturelog==0.7,pytest-cover==1.0.0,wheel==0.24.0
2.7 runtests: PYTHONHASHSEED='554'
2.7 runtests: commands[0] | python setup.py clean --all build_ext --force --inplace
running clean
'build\lib' does not exist -- can't clean it
'build\bdist.win-amd64' does not exist -- can't clean it
'build\scripts-2.7' does not exist -- can't clean it
running build_ext
2.7 runtests: commands[1] | py.test --cov=src --cov-report=term-missing -vv
============================= test session starts =============================
platform win32 -- Python 2.7.10 -- py-1.4.28 -- pytest-2.7.1 -- C:\Users\Christer\code\python\python-nameless\.tox\2.7\Scripts\python.exe
rootdir: C:\Users\Christer\code\python\python-nameless, inifile: setup.cfg
plugins: capturelog, cover
collected 15 items

AUTHORS.rst PASSED
CHANGELOG.rst PASSED
CONTRIBUTING.rst PASSED
README.rst PASSED
docs/authors.rst PASSED
docs/changelog.rst PASSED
docs/contributing.rst PASSED
docs/index.rst PASSED
docs/installation.rst PASSED
docs/readme.rst PASSED
docs/usage.rst PASSED
docs/reference/index.rst PASSED
docs/reference/nameless.rst PASSED
tests/test_nameless.py::test_bin PASSED
tests/test_nameless.py::test_mod PASSED
--------------- coverage: platform win32, python 2.7.10-final-0 ---------------
Name                    Stmts   Miss Branch BrMiss     Cover   Missing
----------------------------------------------------------------------
src\nameless\__init__       1      0      0      0   100.00%
src\nameless\__main__       7      2      2      1    66.67%   13, 16
----------------------------------------------------------------------
TOTAL                       8      2      2      1    70.00%

========================== 15 passed in 0.52 seconds ==========================
___________________________________ summary ___________________________________
  2.7: commands succeeded
  congratulations :)
```

I can confirm that ``pytest-cover.pth`` is present in ``.tox\2.7\Lib\site-packages`` after running.

**Comment by cmeeren** [comment] 2015-06-06 15:27
I'm running the command from Python 3.4, by the way. Here are the packages installed in that environment:

```
$ conda list
# packages in environment at C:\Anaconda\envs\py34:
#
You are using pip version 7.0.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
_license                  1.1                      py34_0
alabaster                 0.7.4                     <pip>
anaconda                  2.2.0                np19py34_0
argcomplete               0.8.4                    py34_0
astroid                   1.3.4                    py34_0
astropy                   1.0.1                np19py34_0
babel                     1.3                       <pip>
bcolz                     0.8.1                np19py34_0
beautiful-soup            4.3.2                    py34_1
beautifulsoup4            4.3.2                     <pip>
binstar                   0.10.1                   py34_3
bitarray                  0.8.1                    py34_1
blaze                     0.7.3                     <pip>
blaze-core                0.7.3                np19py34_0
blz                       0.6.2                np19py34_0
bokeh                     0.8.1                np19py34_1
boto                      2.36.0                   py34_0
certifi                   14.05.14                 py34_0
cffi                      0.9.2                    py34_0
clyent                    0.3.4                    py34_0
colorama                  0.3.3                    py34_0
configobj                 5.0.6                    py34_0
cov-core                  1.15.0                    <pip>
coverage                  3.7.1                     <pip>
cryptography              0.8                      py34_1
cython                    0.22                     py34_0
cytoolz                   0.7.2                    py34_0
datashape                 0.4.4                np19py34_1
decorator                 3.4.0                    py34_0
detox                     0.10.0                    <pip>
docutils                  0.12                     py34_1
dynd-python               0.6.5                np19py34_0
eventlet                  0.17.4                    <pip>
fastcache                 1.0.2                    py34_0
flask                     0.10.1                   py34_1
greenlet                  0.4.5                    py34_0
h5py                      2.4.0                np19py34_0
ipython                   3.0.0                    py34_1
ipython-notebook          3.0.0                    py34_2
ipython-qtconsole         3.0.0                    py34_1
itsdangerous              0.24                     py34_0
jdcal                     1.0                      py34_0
jedi                      0.8.1                    py34_0
jinja2                    2.7.3                    py34_2
jsonschema                2.4.0                    py34_0
launcher                  1.0.0                         1
llvmlite                  0.2.2                    py34_1
logilab-common            0.63.2                   py34_0
lxml                      3.4.2                    py34_0
markupsafe                0.23                     py34_0
matplotlib                1.4.3                np19py34_1
menuinst                  1.0.4                    py34_0
mistune                   0.5.1                    py34_0
mock                      1.0.1                    py34_0
multipledispatch          0.4.7                    py34_0
networkx                  1.9.1                    py34_0
nltk                      3.0.2                np19py34_0
node-webkit               0.10.1                        0
nose                      1.3.4                    py34_1
numba                     0.17.0               np19py34_0
numexpr                   2.3.1                np19py34_0
numpy                     1.9.2                    py34_0
odo                       0.3.1                np19py34_0
openpyxl                  1.8.5                    py34_0
pandas                    0.15.2               np19py34_1
patsy                     0.3.0                np19py34_0
pep8                      1.6.2                    py34_0
pillow                    2.7.0                    py34_0
pip                       7.0.1                    py34_0
pkginfo                   1.2.1                     <pip>
pluggy                    0.3.0                     <pip>
ply                       3.4                      py34_0
psutil                    2.2.1                    py34_0
py                        1.4.27                   py34_0
pyasn1                    0.1.7                    py34_0
pybtex                    0.18                      <pip>
pycosat                   0.6.1                    py34_0
pycparser                 2.10                     py34_0
pycrypto                  2.6.1                    py34_3
pyflakes                  0.8.1                    py34_0
pygments                  2.0.2                    py34_0
pylint                    1.4.2                    py34_0
pyopenssl                 0.14                     py34_0
pyparsing                 2.0.3                    py34_0
pyqt                      4.10.4                   py34_1
pyreadline                2.0                      py34_0
pytables                  3.1.1                np19py34_1
pytest                    2.7.1                    py34_0
pytest-cov                1.8.1                     <pip>
pytest-mock               0.5.0                     <pip>
python                    3.4.3                         0
python-dateutil           2.4.1                    py34_0
pytz                      2015.2                   py34_0
pywin32                   219                      py34_0
pyyaml                    3.11                     py34_0
pyzmq                     14.5.0                   py34_0
requests                  2.6.0                    py34_0
rope                      0.9.4                    py34_1
rope-py3k-0.9.4           1                         <pip>
runipy                    0.1.3                    py34_0
scikit-image              0.11.2               np19py34_0
scikit-learn              0.15.2               np19py34_0
scipy                     0.15.1               np19py34_0
setuptools                17.0                     py34_0
six                       1.9.0                    py34_0
snowballstemmer           1.2.0                     <pip>
sockjs-tornado            1.0.1                    py34_0
sphinx                    1.2.3                    py34_0
sphinx-rtd-theme          0.1.8                     <pip>
spyder                    2.3.4                    py34_1
spyder-app                2.3.4                    py34_0
sqlalchemy                0.9.9                    py34_0
statsmodels               0.6.1                np19py34_0
sympy                     0.7.6                    py34_0
tables                    3.1.1                     <pip>
toolz                     0.7.1                    py34_0
tornado                   4.1                      py34_0
tox                       2.0.1                     <pip>
twine                     1.5.0                     <pip>
ujson                     1.33                     py34_0
virtualenv                13.0.1                    <pip>
werkzeug                  0.10.1                   py34_0
wheel                     0.24.0                    <pip>
winpdb                    1.3.6                     <pip>
xlrd                      0.9.3                    py34_0
xlsxwriter                0.6.7                    py34_0
xlwings                   0.3.4                    py34_0
```

**Comment by ionelmc** [comment] 2015-06-06 15:50
Still covered under 3.4: https://travis-ci.org/ionelmc/python-nameless/jobs/65685191#L161

Did you say you use conda or something like that?

**Comment by ionelmc** [comment] 2015-06-06 15:51
Oh.

Let me try this on Windows. Maybe it's specific to that.

**Comment by ionelmc** [comment] 2015-06-06 18:17
Turns out it's a bug in `coverage` :grin: - it doesn't correctly normalize the drive.

**Comment by cmeeren** [comment] 2015-06-06 18:58
Oh, right. Should work on Travis, then. Are you [reporting it](https://bitbucket.org/ned/coveragepy/issues?status=new&status=open)?

And are you releasing your plugin on pypi anytime soon?

**Comment by ionelmc** [comment] 2015-06-06 19:38
Waiting few days for some response from maintainer of pytest-cov.

About coverage: https://bitbucket.org/ned/coveragepy/pull-request/54/correct-path-normalization-on-windows/diff - post your results there to get it merged faster.

**Comment by cmeeren** [comment] 2015-06-06 19:44
Done (I think that was what you meant).

**Comment by cmeeren** [comment] 2015-06-06 19:47
Interestingly, it still doesn't work on Travis. See e.g. [this log](https://travis-ci.org/cmeeren/latexdiffcite/jobs/65713248), coverage at the bottom. Shouldn't it work, since Travis uses linux?

**Comment by ionelmc** [comment] 2015-06-06 21:33
It works now ;-)

Seems pytest-cov has some bug ...


Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by Hikari9** [comment] 2019-03-14 07:23
Hi, if I may add, I know this is an old issue. I was able to solve this problem by doing the following (I'm using pytest-cov).

## Running `__main__` in Pytest (with coverage)

Say I want to run `__main__` method of `python package/foo/bar.py` in pytest.

1. Add `parallel = true` in setup.cfg under `[coverage:run]`
    
    ```cfg
    ; Example: setup.cfg, pytest.ini

    [coverage:run]
    parallel = true
    ```

    or if you're using `.coveragerc`

    ```cfg
    ; Example: .coveragerc

    [run]
    parallel = true
    ```

2. Add the following fixture:

    ```python
    # Example: tests/conftest.py

    import sys
    import shlex
    import subprocess

    @pytest.fixture(scope='session')
    def run_main():

        def main(module, **kwargs):

            # will run: python -m coverage run -m <module>
            command = [sys.executable, '-m', 'coverage', 'run', '-m'] + shlex.split('module')

            # pass environment to subprocess
            kwargs['env'] = kwargs.get('env', os.environ.copy())

            return subprocess.Popen(command, **kwargs)

        return main
    ```

    In the test, I can do:

    ```python
    # Example: test/test_foo.py

    import subprocess

    def test_foo_bar(run_main):
        with run_main('foo.bar', stdout=subprocess.PIPE) as proc:
            stdout, stderr = proc.communicate(timeout=5)
            # do other stuff with proc
    ```

**Comment by ionelmc** [comment] 2019-03-14 11:04
@Hikari9 that sounds like a pytest-cov bug, [provide a reproducer](https://github.com/pytest-dev/pytest-cov/issues/new) and I'll take a look.

I think this issue can be closed, meanwhile I took over maintenance for pytest-cov and fixed lots of problems,

**Closed by ionelmc** 2019-03-14 11:04 UTC
